In [1]:
a=15
b=87
a*b

1305

In [2]:
import numpy as np
height = np.array([170,172,175,167,166])
weight = np.array([62,63,72,57,63])
print(weight)
print(height)

[62 63 72 57 63]
[170 172 175 167 166]


In [27]:
bmi = (weight)/((height/100)**2)
print(bmi)

[21.4532872  21.29529475 23.51020408 20.43816558 22.86253448]


In [29]:
bmi[bmi>21.5]

array([23.51020408, 22.86253448])

In [33]:
bmi[bmi>16]

array([21.4532872 , 21.29529475, 23.51020408, 20.43816558, 22.86253448])

In [4]:
matrix=np.array([[65,60,90],[85,90,40],[80,95,45]])
print(matrix)

[[65 60 90]
 [85 90 40]
 [80 95 45]]


In [11]:
print(matrix.ndim)
print(matrix.shape)
print(matrix.dtype)
print(len(matrix))
print(matrix.size)
print(len(matrix[1]))

2
(3, 3)
int32
3
9
3


In [18]:
matar = np.arange(10)
print(mat)
matarr=np.arange(2,13,2)
print(matarr)
matlin = np.linspace(1,3,5)
print(matlin)

[0 1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12]
[1.  1.5 2.  2.5 3. ]


In [21]:
matzero = np.zeros((5,3))
print(matzero)
matone=np.ones((2,5))
print(matone)
matfull = np.full((4,3),2)
print(matfull)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]


In [24]:
matran = np.random.random_sample(5)
print(matran)
matranint = np.random.randint(20,30,[4,3])
print(matranint)
matrannor = np.random.normal(173,3,[3,3])
print(matrannor)

[0.96726001 0.16885488 0.01551893 0.96138555 0.07615778]
[[24 27 21]
 [22 25 29]
 [20 28 22]
 [29 26 24]]
[[166.14082473 174.46965746 175.38161489]
 [172.34214742 169.10888111 176.57758757]
 [174.80310364 168.55839429 166.16582948]]


In [26]:
matiden = np.eye(3)
print(matiden)
matdia = np.diag([2,2,3,5])
print(matdia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[2 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 5]]
